version: '3.8'

services:
  mongo:
    image: mongo
    container_name: ms_mongo
    volumes:
      - './data_mongo:/data/db'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    command:
      - --auth
    restart: always
    ports:
      - '${MONGO_PORT}:27017'
  postgres:
    image: postgres
    container_name: ms_postgre
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes: 
      - .:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT}:5432'
    restart: unless-stopped
  rabbitmq:
    image: rabbitmq
    container_name: ms_rabbitmq
    ports:
      - 5672:5672
  api-auth:
    image: api-auth
    container_name: api-auth
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      target: development
    command: pnpm run start:dev
    env_file:
      - config/.env.dev.local
    ports:
      - '9000:9000'

