version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.10.7-management
    container_name: ms_rabbitmq
    ports:
      - ${RABBIT_PORT}:5672
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit
    volumes:
     - ./docker:/var/lib/rabbitmq
  mongo:
    image: mongo
    container_name: ms_mongo
    volumes:
      - './docker/data_mongo:/data/db'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    command:
      - --auth
    restart: always
    ports:
      - '${MONGO_PORT}:27017'
  postgres:
    image: postgres
    container_name: ms_postgre
    environment:
      #Note that POSTGRES_USER creates a user in Postgres, not in /etc/passwd
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes: 
      - ./docker:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT}:5432'
    restart: unless-stopped
  
 